/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.func_DAO;
import Model.func;
import javax.swing.JOptionPane;

/**
 *
 * @author Murylo
 */
public class Cadastro_GUI extends javax.swing.JFrame {

    /**
     * Creates new form login_GUI
     */
    public Cadastro_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        senha_txt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        nome_txt = new javax.swing.JTextField();
        tel_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 51, 51));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CADASTRO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(580, 40, 280, 50);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(890, 0, 70, 32);

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 35)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 220, 170, 30);

        email_txt.setBackground(new java.awt.Color(142, 135, 135));
        email_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        email_txt.setForeground(new java.awt.Color(255, 255, 255));
        email_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(email_txt);
        email_txt.setBounds(650, 200, 300, 30);

        jButton1.setBackground(new java.awt.Color(54, 51, 51));
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Clique aqui");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(730, 400, 110, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Email :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(490, 190, 170, 50);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Já possui uma conta ?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(600, 400, 130, 30);

        senha_txt.setBackground(new java.awt.Color(142, 135, 135));
        senha_txt.setForeground(new java.awt.Color(255, 255, 255));
        senha_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(senha_txt);
        senha_txt.setBounds(650, 340, 300, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 35)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Senha :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 330, 170, 50);

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 35)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Telefone :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 260, 170, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuário :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 130, 160, 50);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CADASTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(630, 470, 210, 48);

        nome_txt.setBackground(new java.awt.Color(142, 135, 135));
        nome_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nome_txt.setForeground(new java.awt.Color(255, 255, 255));
        nome_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(nome_txt);
        nome_txt.setBounds(650, 140, 300, 30);

        tel_txt.setBackground(new java.awt.Color(142, 135, 135));
        tel_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tel_txt.setForeground(new java.awt.Color(255, 255, 255));
        tel_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tel_txt);
        tel_txt.setBounds(660, 270, 290, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoprincipalvista (1).jpeg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 473, 553);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(976, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

//        JOptionPane.showMessageDialog(null, "Funcionário Cadastrado");
        func f = new func();
        func_DAO dao = new func_DAO();

        f.setNome(nome_txt.getText());
        f.setEmail(email_txt.getText());
        String telefone = tel_txt.getText();
        if (!telefone.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "O telefone deve conter apenas números.");
            return;
        }
        f.setTelefone(telefone);
        f.setSenha(senha_txt.getText());

        dao.cadastrar(f);

        nome_txt.setText("");
        email_txt.setText("");
        tel_txt.setText("");
        senha_txt.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField email_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField nome_txt;
    public static javax.swing.JPasswordField senha_txt;
    public static javax.swing.JTextField tel_txt;
    // End of variables declaration//GEN-END:variables
}
