/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PedidoProduto_DAO;
import Controller.Pedido_DAO;
import Model.PedidoProduto;
import Model.comanda;
import Model.pedido;
import Model.produto;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Murylo
 */
public class Pedido_GUI extends javax.swing.JFrame {

    private void customizeMenuBar(JMenuBar menuBar) {

        menuBar.setUI(new BasicMenuBarUI() {

            @Override
            public void paint(Graphics g, JComponent c) {
                g.setColor(Color.black);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }

        });

        MenuElement[] menus = menuBar.getSubElements();

        for (MenuElement menuElement : menus) {

            JMenu menu = (JMenu) menuElement.getComponent();
            changeComponentColors(menu);
            menu.setOpaque(true);

            MenuElement[] menuElements = menu.getSubElements();

            for (MenuElement popupMenuElement : menuElements) {

                JPopupMenu popupMenu = (JPopupMenu) popupMenuElement.getComponent();
                popupMenu.setBorder(null);

                MenuElement[] menuItens = popupMenuElement.getSubElements();

                for (MenuElement menuItemElement : menuItens) {

                    JMenuItem menuItem = (JMenuItem) menuItemElement.getComponent();
                    changeComponentColors(menuItem);
                    menuItem.setOpaque(true);

                }
            }
        }
    }

    private void changeComponentColors(Component comp) {
        comp.setBackground(Color.black);
        comp.setForeground(Color.white);
    }

    public Pedido_GUI() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) pedidos_table.getModel();
        pedidos_table.setAutoCreateRowSorter(false);
        readJTable();
        customizeMenuBar(barrinha);

    }
    
    

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) pedidos_table.getModel();
        PedidoProduto_DAO pdao = new PedidoProduto_DAO();

        modelo.setNumRows(0);
        List<PedidoProduto> pedidos = pdao.read();
        
         Collections.sort(pedidos, new Comparator<PedidoProduto>() {
        @Override
        public int compare(PedidoProduto p1, PedidoProduto p2) {
            return Integer.compare(p1.getPddId(), p2.getPddId());
        }
    });
        
        for (PedidoProduto pp : pedidos) {
            modelo.addRow(new Object[]{
                pp.getPddId(),
                pp.getPdtNome(),
                pp.getPdtId(),
                pp.getPdtPreco(),
                pp.getQuantidade(),
                pp.getCmaId()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        nomepdd_txt = new javax.swing.JLabel();
        obs_txt = new javax.swing.JTextField();
        qtd_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        precopdd_txt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cma_id_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idpdtpdd_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidos_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        limpar_btn = new javax.swing.JButton();
        barrinha = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Início");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 51, 51));
        jPanel1.setLayout(null);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.png"))); // NOI18N
        panelImage1.setPreferredSize(new java.awt.Dimension(973, 530));
        panelImage1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pedido");
        panelImage1.add(jLabel2);
        jLabel2.setBounds(420, 10, 130, 50);

        nomepdd_txt.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        nomepdd_txt.setForeground(new java.awt.Color(255, 255, 255));
        panelImage1.add(nomepdd_txt);
        nomepdd_txt.setBounds(450, 90, 290, 30);

        obs_txt.setBackground(new java.awt.Color(103, 103, 103));
        obs_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        obs_txt.setForeground(new java.awt.Color(255, 255, 255));
        obs_txt.setSelectionColor(new java.awt.Color(153, 153, 153));
        obs_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obs_txtActionPerformed(evt);
            }
        });
        panelImage1.add(obs_txt);
        obs_txt.setBounds(650, 150, 290, 30);

        qtd_txt.setBackground(new java.awt.Color(103, 103, 103));
        qtd_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        qtd_txt.setForeground(new java.awt.Color(255, 255, 255));
        qtd_txt.setSelectionColor(new java.awt.Color(153, 153, 153));
        qtd_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtd_txtActionPerformed(evt);
            }
        });
        panelImage1.add(qtd_txt);
        qtd_txt.setBounds(160, 150, 73, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Id Comanda :");
        panelImage1.add(jLabel5);
        jLabel5.setBounds(270, 150, 130, 30);

        precopdd_txt.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        precopdd_txt.setForeground(new java.awt.Color(255, 255, 255));
        panelImage1.add(precopdd_txt);
        precopdd_txt.setBounds(840, 90, 70, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id Produto : ");
        panelImage1.add(jLabel7);
        jLabel7.setBounds(50, 90, 120, 30);

        cma_id_txt.setBackground(new java.awt.Color(103, 103, 103));
        cma_id_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cma_id_txt.setForeground(new java.awt.Color(255, 255, 255));
        cma_id_txt.setSelectionColor(new java.awt.Color(153, 153, 153));
        cma_id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cma_id_txtActionPerformed(evt);
            }
        });
        panelImage1.add(cma_id_txt);
        cma_id_txt.setBounds(410, 150, 73, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Observação :");
        panelImage1.add(jLabel8);
        jLabel8.setBounds(510, 150, 140, 30);

        idpdtpdd_txt.setBackground(new java.awt.Color(103, 103, 103));
        idpdtpdd_txt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        idpdtpdd_txt.setForeground(new java.awt.Color(255, 255, 255));
        idpdtpdd_txt.setSelectionColor(new java.awt.Color(153, 153, 153));
        idpdtpdd_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpdtpdd_txtActionPerformed(evt);
            }
        });
        panelImage1.add(idpdtpdd_txt);
        idpdtpdd_txt.setBounds(180, 90, 73, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantidade :");
        panelImage1.add(jLabel9);
        jLabel9.setBounds(20, 150, 140, 30);

        jButton4.setBackground(new java.awt.Color(37, 36, 36));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton4);
        jButton4.setBounds(290, 90, 60, 30);

        jButton5.setBackground(new java.awt.Color(37, 36, 36));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit0 (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton5);
        jButton5.setBounds(470, 210, 60, 30);

        jButton6.setBackground(new java.awt.Color(37, 36, 36));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar (1).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton6);
        jButton6.setBounds(360, 210, 50, 30);

        jButton7.setBackground(new java.awt.Color(37, 36, 36));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fehcar (1).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelImage1.add(jButton7);
        jButton7.setBounds(590, 210, 50, 30);

        pedidos_table.setBackground(new java.awt.Color(103, 103, 103));
        pedidos_table.setForeground(new java.awt.Color(255, 255, 255));
        pedidos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Pedido", "Nome", "Id_Produto", "Preço_Unit", "Quantidade", "Id_Comanda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pedidos_table.setAutoscrolls(false);
        pedidos_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidos_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pedidos_table);

        panelImage1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 980, 250);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome:");
        panelImage1.add(jLabel10);
        jLabel10.setBounds(370, 90, 70, 30);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Preço :");
        panelImage1.add(jLabel11);
        jLabel11.setBounds(750, 90, 70, 30);

        limpar_btn.setBackground(new java.awt.Color(37, 36, 36));
        limpar_btn.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        limpar_btn.setForeground(new java.awt.Color(255, 255, 255));
        limpar_btn.setText("Limpar");
        limpar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_btnActionPerformed(evt);
            }
        });
        panelImage1.add(limpar_btn);
        limpar_btn.setBounds(860, 30, 100, 30);

        jPanel1.add(panelImage1);
        panelImage1.setBounds(0, 0, 980, 530);

        barrinha.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Início");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Tela Inicial");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        barrinha.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Pedido");
        barrinha.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 0, 0));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Comanda");

        jMenuItem4.setText("Manipular Comandas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        barrinha.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Cardápio");

        jMenuItem5.setText("Manipular Produtos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        barrinha.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(0, 0, 0));
        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Caixa");

        jMenuItem6.setText("Fechar Comanda");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        barrinha.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(0, 0, 0));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("Cozinha");

        jMenuItem7.setText("Visualizar Pedidos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        barrinha.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(0, 0, 0));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setText("Ajuda");

        jMenuItem8.setText("Arquivo de Ajuda");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        barrinha.add(jMenu7);

        jMenu8.setBackground(new java.awt.Color(0, 0, 0));
        jMenu8.setForeground(new java.awt.Color(255, 255, 255));
        jMenu8.setText("Sair");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        barrinha.add(jMenu8);

        setJMenuBar(barrinha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(976, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        String x = JOptionPane.showInputDialog(null, "Deseja realmente fechar ?"
                + " \n1 - Sim"
                + " \n2 - Não "
        );
        int op = Integer.parseInt(x);

        if (op == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void obs_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obs_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obs_txtActionPerformed

    private void qtd_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtd_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtd_txtActionPerformed

    private void cma_id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cma_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cma_id_txtActionPerformed

    private void idpdtpdd_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpdtpdd_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpdtpdd_txtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        produto pdt = new produto();
        Pedido_DAO dao = new Pedido_DAO();
        pdt.setId(Integer.parseInt(idpdtpdd_txt.getText()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
        dao.consul(pdt);
        readJTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

              // TODO add your handling code here:
            pedido p = new pedido();
            Pedido_DAO dao = new Pedido_DAO();
            p.setCma_id(Integer.parseInt(cma_id_txt.getText()));
            p.setPdt_id(Integer.parseInt(idpdtpdd_txt.getText()));
            p.setObs(obs_txt.getText());
            p.setQuantidade(Integer.parseInt(qtd_txt.getText()));
            p.setId(Integer.parseInt(pedidos_table.getValueAt(pedidos_table.getSelectedRow(), 0).toString()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
            dao.update(p);
            readJTable();
            idpdtpdd_txt.setText("");
            nomepdd_txt.setText("");
            precopdd_txt.setText("");
            qtd_txt.setText("");
            cma_id_txt.setText("");
            obs_txt.setText("");

        
//        idpdt_txt.setText("");
//        nomepdt_txt.setText("");
//        precopdt_txt.setText("");
//        tipopdt_txt.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        pedido p = new pedido();
        comanda c = new comanda();
        Pedido_DAO dao = new Pedido_DAO();
        c.setId(Integer.parseInt(cma_id_txt.getText()));
        p.setCma_id(Integer.parseInt(cma_id_txt.getText()));
        p.setPdt_id(Integer.parseInt(idpdtpdd_txt.getText()));
        p.setObs(obs_txt.getText());
        p.setQuantidade(Integer.parseInt(qtd_txt.getText()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
        dao.create(p,c);
        readJTable();
        idpdtpdd_txt.setText("");
        nomepdd_txt.setText("");
        precopdd_txt.setText("");
        obs_txt.setText("");
        qtd_txt.setText("");
//        cma_id_txt.setText("");

//        idpdt_txt.setText("");
//        nomepdt_txt.setText("");
//        precopdt_txt.setText("");
//        tipopdt_txt.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
            pedido p = new pedido();
            Pedido_DAO dao = new Pedido_DAO();
            p.setId(Integer.parseInt(pedidos_table.getValueAt(pedidos_table.getSelectedRow(), 0).toString()));
//        p.setTipo(tipopdt_cmb.getSelectedItem().toString().toLowerCase());
            dao.delete(p);
            idpdtpdd_txt.setText("");
            nomepdd_txt.setText("");
            precopdd_txt.setText("");
            qtd_txt.setText("");
            cma_id_txt.setText("");
            obs_txt.setText("");
            readJTable();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Inicio_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new Comanda_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new Cardapio_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new Caixa_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new Cozinha_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void pedidos_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidos_tableMouseClicked
        // TODO add your handling code here:
        if (pedidos_table.getSelectedRow() != -1) {
            idpdtpdd_txt.setText(pedidos_table.getValueAt(pedidos_table.getSelectedRow(), 2).toString());
            nomepdd_txt.setText(pedidos_table.getValueAt(pedidos_table.getSelectedRow(), 1).toString());
            precopdd_txt.setText(pedidos_table.getValueAt(pedidos_table.getSelectedRow(), 3).toString());
            qtd_txt.setText(pedidos_table.getValueAt(pedidos_table.getSelectedRow(), 4).toString());
            cma_id_txt.setText(pedidos_table.getValueAt(pedidos_table.getSelectedRow(), 5).toString());
            obs_txt.setText("");
        }
    }//GEN-LAST:event_pedidos_tableMouseClicked

    private void limpar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_btnActionPerformed
        // TODO add your handling code here:

        idpdtpdd_txt.setText("");
        nomepdd_txt.setText("");
        precopdd_txt.setText("");
        qtd_txt.setText("");
        cma_id_txt.setText("");
        obs_txt.setText("");

    }//GEN-LAST:event_limpar_btnActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open(new File("C:\\Users\\Murylo\\Downloads\\juda1.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(Pedido_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuBar barrinha;
    private javax.swing.JTextField cma_id_txt;
    private javax.swing.JTextField idpdtpdd_txt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar_btn;
    public static javax.swing.JLabel nomepdd_txt;
    private javax.swing.JTextField obs_txt;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTable pedidos_table;
    public static javax.swing.JLabel precopdd_txt;
    private javax.swing.JTextField qtd_txt;
    // End of variables declaration//GEN-END:variables
}
